version: '3'

services:
  database:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: social-network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - database

  server:
    restart:
      always
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    links:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_NAME: social-network
      JWT_SECRET: jwt
      REFRESH_SECRET: refresh
      ACCESS_SECRET: access

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/client/.next
    ports:
      - "3000:3000"
    links:
      - database
      - server

volumes:
  pg_data:
